# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
=begin
Team.create(name: 'New Zealand', world_ranking: '1', star_player: 'Dan Carter', image_url: 'logo_All_Blacks.jpg', star_player_image: 'dancarter.jpg')
Team.create(name: 'Australia', world_ranking: '3', star_player: 'Nathan Sharpe', image_url: 'logo_Australia.jpg', star_player_image: 'nathansharpe.jpg')
Team.create(name: 'South Africa', world_ranking: '2', star_player: 'Bryan Habana', image_url: 'logo_South_Africa.jpg', star_player_image: 'brianhavana.jpg')
Team.create(name: 'Argentina', world_ranking: '8', star_player: 'Juan Martin Fernanadez Lobbe', image_url: 'logo_pumas.jpg', star_player_image: 'juanlobbe.jpg')



Player.destroy_all
Player.create(first_name: 'Agustin', last_name: 'Creevy', position: 'Hooker', player_number: '16', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Eusebio', last_name: 'Guinazu', position: 'Hooker', player_number: '2', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Bruno', last_name: 'Postiglioni', position: 'Hooker', player_number: '23', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Marcos', last_name: 'Ayerza', position: 'Prop', player_number: '4', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Maxi', last_name: 'Bustos', position: 'Prop', player_number: '5', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Juan', last_name: 'Figallo', position: 'Prop', player_number: '3', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Juan', last_name: 'Orlandi', position: 'Prop', player_number: '17', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Rodrigo', last_name: 'Roncero', position: 'Prop', player_number: '1', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Patricio', last_name: 'Albacete', position: 'Lock', player_number: '5', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Julio', last_name: 'Farias Cabello', position: 'Lock', player_number: '6', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Manuel', last_name: 'Carriza', position: 'Lock', player_number: '4', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Tomas', last_name: 'Vallejos', position: 'Lock', player_number: '12', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Tomas', last_name: 'De la Vega', position: 'Flanker', player_number: '25', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Alvaro', last_name: 'Galindo', position: 'Flanker', player_number: '14', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Juan Manuel', last_name: 'Leguizamon', position: 'Flanker', player_number: '7', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Tomas', last_name: 'Leonardi', position: 'Flanker', player_number: '19', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Juan Martin', last_name: 'Fernandez Lobbe', position: 'Number 8', player_number: '8', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Leandro', last_name: 'Senatore', position: 'Number 8', player_number: '18', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Tomas', last_name: 'Cubelli', position: 'Scrum-half', player_number: '33', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Agustin', last_name: 'Figuerola', position: 'Scrum-half', player_number: '30', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Nicolas', last_name: 'Vergallo', position: 'Scrum-half', player_number: '20', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Santiago', last_name: 'Fernandez', position: 'Fly half', player_number: '12', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Juan Martin', last_name: 'Hernandez', position: 'Fly half', player_number: '10', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Martin', last_name: 'Landajo', position: 'Fly half', player_number: '9', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Marcelo', last_name: 'Bosch', position: 'Centre', player_number: '13', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Rafael', last_name: 'Carballo', position: 'Centre', player_number: '26', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Martin', last_name: 'Rodriguez', position: 'Centre', player_number: '27', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Nicolas', last_name: 'Sanchez', position: 'Centre', player_number: '21', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Horacio', last_name: 'Agulla', position: 'Wing', player_number: '11', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Gonzalo', last_name: 'Camacho', position: 'Wing', player_number: '14', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Juan', last_name: 'Imhoff', position: 'Wing', player_number: '22', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Manuel', last_name: 'Montero', position: 'Wing', player_number: '32', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Martin', last_name: 'Bustos', position: 'Fullback', player_number: '24', team_name: 'Argentina', team_id: '16')
Player.create(first_name: 'Lucas', last_name: 'Gonzalez Amorosino', position: 'Fullback', player_number: '15', team_name: 'Argentina', team_id: '16')


Player.create(first_name: 'James', last_name: 'Slipper', position: 'Hooker', player_number: '1', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'Tatafu', last_name: 'Polota-Nau', position: 'Hooker', player_number: '2', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'Ben', last_name: 'Alexander', position: 'Prop', player_number: '3', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'Kane', last_name: 'Douglas', position: 'Lock', player_number: '4', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'Nathan', last_name: 'Sharpe', position: 'Lock', player_number: '5', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'Sitaleki', last_name: 'Timani', position: 'Lock', player_number: '6', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'Michael', last_name: 'Hooper', position: 'Flanker', player_number: '7', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'Radike', last_name: 'Samo', position: 'Number 8', player_number: '8', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'Nick', last_name: 'Phipps', position: 'Scrum-half', player_number: '9', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'Kurtley', last_name: 'Beale', position: 'Fullback', player_number: '10', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'Digby', last_name: 'Loane', position: 'Wing', player_number: '11', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'Pat', last_name: 'McCabe', position: 'Centre', player_number: '12', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'Ben', last_name: 'Tapuai', position: 'Centre', player_number: '13', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'Nick', last_name: 'Cummins', position: 'Wing', player_number: '14', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'Mike', last_name: 'Harris', position: 'Centre', player_number: '15', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'Saia', last_name: 'Faingaa', position: 'Hooker', player_number: '16', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'Benn', last_name: 'Robinson', position: 'Prop', player_number: '17', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'Dave', last_name: 'Dennis', position: 'Flanker', player_number: '18', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'Scott', last_name: 'Higginbotham', position: 'Number 8', player_number: '19', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'Brett', last_name: 'Sheehan', position: 'Hooker', player_number: '21', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'Dom', last_name: 'Shipperley', position: 'Wing', player_number: '22', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'Stephen', last_name: 'Moore', position: 'Hooker', player_number: '23', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'Sekope', last_name: 'Kepu', position: 'Prop', player_number: '24', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'James', last_name: 'Slipper', position: 'Prop', player_number: '25', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'Rob', last_name: 'Simmons', position: 'Lock', player_number: '26', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'Liam', last_name: 'Gill', position: 'Flanker', player_number: '27', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'David', last_name: 'Pocock', position: 'Flanker', player_number: '28', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'Jake', last_name: 'Schtaz', position: 'flanker', player_number: '29', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'Will', last_name: 'Genia', position: 'Scrum-half',player_number: '30', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'Nic', last_name: 'White', position: 'Scrum-half', player_number: '31', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'Berrick', last_name: 'Barnes', position: 'Fly half', player_number: '32', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'Quade', last_name: 'Cooper', position: 'Fly half', player_number: '33', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'Anthony', last_name: 'Faingaa', position: 'Centre', player_number: '34', team_name: 'Australia', team_id: '14')
Player.create(first_name: 'Adam', last_name: 'Ashley-Cooper', position: 'Wing', player_number: '35', team_name: 'Australia', team_id: '14')

Player.create(first_name: 'Craig', last_name: 'Burden', position: 'Hooker', player_number: '27', team_name: 'South Africa', team_id: '15')
Player.create(first_name: 'Tiaan', last_name: 'Lienbenberg', position: 'Hooker',player_number: '16', team_name: 'South Africa', team_id: '15')
Player.create(first_name: 'Adriaan', last_name: 'Strauss', position: 'Hooker', player_number: '2', team_name: 'South Africa', team_id: '15')
Player.create(first_name: 'Pat', last_name: 'Ciliers', position: 'Prop', player_number: '26', team_name: 'South Africa', team_id: '15')
Player.create(first_name: 'Jannie', last_name: 'du Plessis', position: 'Prop', player_number: '3', team_name: 'South Africa', team_id: '15')
Player.create(first_name: 'Dean', last_name: 'Greyling', position: 'Prop', player_number: '28', team_name: 'South Africa', team_id: '15')
Player.create(first_name: 'Tendai', last_name: 'Mtawarira', position: 'Prop', player_number: '1', team_name: 'South Africa', team_id: '15')
Player.create(first_name: 'Andries', last_name: 'Bekker', position: 'Lock', player_number: '5', team_name: 'South Africa', team_id: '15')
Player.create(first_name: 'Eben', last_name: 'Etzebeth', position: 'Lock', player_number: '4', team_name: 'South Africa', team_id: '15')
Player.create(first_name: 'Juandre', last_name: 'Kruger', position: 'Lock', player_number: '29', team_name: 'South Africa', team_id: '15')
Player.create(first_name: 'Flip', last_name: 'van der Merwe', position: 'Lock', player_number: '18', team_name: 'South Africa', team_id: '15')
Player.create(first_name: 'Marcell', last_name: 'Coetzee', position: 'Flanker', player_number: '19', team_name: 'South Africa', team_id: '15')
Player.create(first_name: 'Francois', last_name: 'Louw', position: 'Flanker', player_number: '6', team_name: 'South Africa', team_id: '15')
Player.create(first_name: 'Jacques', last_name: 'Potgieter', position: 'Flanker', player_number: '25', team_name: 'South Africa', team_id: '15')
Player.create(first_name: 'Williem', last_name: 'Alberts', position: 'Number 8', player_number: '7', team_name: 'South Africa', team_id: '15')
Player.create(first_name: 'Duane', last_name: 'Vermeulen', position: 'Number 8', player_number: '8', team_name: 'South Africa', team_id: '15')
Player.create(first_name: 'Francois', last_name: 'Hougaard', position: 'Scrum-half', player_number: '11', team_name: 'South Africa', team_id: '15')
Player.create(first_name: 'Ruan', last_name: 'Pienaar', position: 'Scrum-half', player_number: '9', team_name: 'South Africa', team_id: '15')
Player.create(first_name: 'Jano', last_name: 'Vermaak', position: 'Scrum-half', player_number: '24', team_name: 'South Africa', team_id: '15')
Player.create(first_name: 'Johan', last_name: 'Goosen', position: 'Fly half', player_number: '10', team_name: 'South Africa', team_id: '15')
Player.create(first_name: 'Morne', last_name: 'Steyn', position: 'Fly half', player_number: '23', team_name: 'South Africa', team_id: '15')
Player.create(first_name: 'Juan', last_name: 'de Jongh', position: 'Centre', player_number: '21', team_name: 'South Africa', team_id: '15')
Player.create(first_name: 'Jean', last_name: 'de Villiers', position: 'Centre', player_number: '12', team_name: 'South Africa', team_id: '15')
Player.create(first_name: 'Francois', last_name: 'Steyn', position: 'Centre', player_number: '30', team_name: 'South Africa', team_id: '15')
Player.create(first_name: 'Bryan', last_name: 'Habana', position: 'Wing', player_number: '14', team_name: 'South Africa', team_id: '15')
Player.create(first_name: 'Lwazi', last_name: 'Mvovo', position: 'Wing', player_number: '31', team_name: 'South Africa', team_id: '15')
Player.create(first_name: 'Zane', last_name: 'Kirchner', position: 'Fullback', player_number: '15', team_name: 'South Africa', team_id: '15')
Player.create(first_name: 'Patrick', last_name: 'Lambie', position: 'Fullback', player_number: '22', team_name: 'South Africa', team_id: '15')
Player.create(first_name: 'Jaco', last_name: 'Taute', position: 'Centre', player_number: '13', team_name: 'South Africa', team_id: '15')
Player.create(first_name: 'Coenie', last_name: 'Oosrhuizen', position: 'Prop', player_number: '17', team_name: 'South Africa', team_id: '15')


Player.create(first_name: 'Andrew', last_name: 'Hore', position: 'Hooker', player_number: '2', team_name: 'New Zealand', team_id: '13')
Player.create(first_name: 'Keven', last_name: 'Mealamu', position: 'Hooker', player_number: '16', team_name: 'New Zealand', team_id: '13')
Player.create(first_name: 'Wyatt', last_name: 'Crockett', position: 'Prop', player_number: '23', team_name: 'New Zealand', team_id: '13')
Player.create(first_name: 'Charlie', last_name: 'Faumuina', position: 'Prop', player_number: '24', team_name: 'New Zealand', team_id: '13')
Player.create(first_name: 'Ben', last_name: 'Franks', position: 'Prop', player_number: '17', team_name: 'New Zealand', team_id: '13')
Player.create(first_name: 'Owen', last_name: 'Franks', position: 'Prop', player_number: '3', team_name: 'New Zealand', team_id: '13')
Player.create(first_name: 'Tony', last_name: 'Woodcock', position: 'Prop', player_number: '1', team_name: 'New Zealand', team_id: '13')
Player.create(first_name: 'Brodie', last_name: 'Retallick', position: 'Lock', player_number: '4', team_name: 'New Zealand', team_id: '13')
Player.create(first_name: 'Luke', last_name: 'Romano', position: 'Lock', player_number: '18', team_name: 'New Zealand', team_id: '13')
Player.create(first_name: 'Sam', last_name: 'Whitelock', position: 'Lock', player_number: '5', team_name: 'New Zealand', team_id: '13')
Player.create(first_name: 'Sam', last_name: 'Cane', position: 'Flanker', player_number: '25', team_name: 'New Zealand', team_id: '13')
Player.create(first_name: 'Richie', last_name: 'McCaw', position: 'Flanker', player_number: '7', team_name: 'New Zealand', team_id: '13')
Player.create(first_name: 'Liam', last_name: 'Messam', position: 'Flanker', player_number: '6', team_name: 'New Zealand', team_id: '13')
Player.create(first_name: 'Adam', last_name: 'Thomson', position: 'Flanker', player_number: '19', team_name: 'New Zealand', team_id: '13')
Player.create(first_name: 'Kieran', last_name: 'Read', position: 'Number 8', player_number: '8', team_name: 'New Zealand', team_id: '13')
Player.create(first_name: 'Victor', last_name: 'Vito', position: 'Number 8', player_number: '26', team_name: 'New Zealand', team_id: '13')
Player.create(first_name: 'Aaron', last_name: 'Smith', position: 'Scrum-half',player_number: '9', team_name: 'New Zealand', team_id: '13')
Player.create(first_name: 'Piri', last_name: 'Weepu', position: 'Scrum-half', player_number: '20', team_name: 'New Zealand', team_id: '13')
Player.create(first_name: 'Dan', last_name: 'Carter', position: 'Fly half', player_number: '10', team_name: 'New Zealand', team_id: '13')
Player.create(first_name: 'Aaron', last_name: 'Cruden', position: 'Fly half', player_number: '21', team_name: 'New Zealand', team_id: '13')
Player.create(first_name: 'Tamati', last_name: 'Ellison', position: 'Centre', player_number: '22', team_name: 'New Zealand', team_id: '13')
Player.create(first_name: 'Maa', last_name: 'Nonu', position: 'Centre', player_number: '12', team_name: 'New Zealand', team_id: '13')
Player.create(first_name: 'Conrad', last_name: 'Smith', position: 'Centre', player_number: '13', team_name: 'New Zealand', team_id: '13')
Player.create(first_name: 'Sonny', last_name: 'Bill Williams', position: 'Centre', player_number: '27', team_name: 'New Zealand', team_id: '13')
Player.create(first_name: 'Hosea', last_name: 'Gear', position: 'Wing', player_number: '11', team_name: 'New Zealand', team_id: '13')
Player.create(first_name: 'Cory', last_name: 'Jane', position: 'Wing', player_number: '14', team_name: 'New Zealand', team_id: '13')
Player.create(first_name: 'Julian', last_name: 'Savea', position: 'Wing',player_number: '28', team_name: 'New Zealand', team_id: '13')
Player.create(first_name: 'Israel', last_name: 'Dag', position: 'Fullback', player_number: '15', team_name: 'New Zealand', team_id: '13')
Player.create(first_name: 'Ben', last_name: 'Smith', position: 'Fullback', player_number: '29', team_name: 'New Zealand', team_id: '13')
Player.create(first_name: 'Beauden', last_name: 'Barrett', position: 'Fullback', player_number: '30', team_name: 'New Zealand', team_id: '13')
=end

Result.create(round:'1', score: '27', team_name: 'New Zealand', team_id: '13', oponent_name:'Australia', opponent_result:'19', opponent_id: '14')
Result.create(round:'1', score: '27', team_name: 'South Africa', team_id: '15', oponent_name:'Argentina', opponent_result:'6', opponent_id: '16')
Result.create(round:'2', score: '0', team_name: 'Australia', team_id: '14', oponent_name:'New Zealand', opponent_result:'22', opponent_id: '13')
Result.create(round:'2', score: '16', team_name: 'Argentina', team_id: '16', oponent_name:'South Africa', opponent_result:'16', opponent_id: '15')
Result.create(round:'3', score: '21', team_name: 'New Zealand', team_id: '13', oponent_name:'Argentina', opponent_result:'5', opponent_id: '16')
Result.create(round:'3', score: '26', team_name: 'Australia', team_id: '14', oponent_name:'South Africa', opponent_result:'19', opponent_id: '15')
Result.create(round:'4', score: '21', team_name: 'New Zealand', team_id: '13', oponent_name:'South Africa', opponent_result:'11', opponent_id: '15')
Result.create(round:'4', score: '23', team_name: 'Australia', team_id: '14', oponent_name:'Argentina', opponent_result:'19', opponent_id: '16')
Result.create(round:'5', score: '31', team_name: 'South Africa', team_id: '15', oponent_name:'Australia', opponent_result:'8', opponent_id: '14')
Result.create(round:'5', score: '15', team_name: 'Argentina', team_id: '16', oponent_name:'New Zealand', opponent_result:'54', opponent_id: '13')
Result.create(round:'6', score: '16', team_name: 'South Africa', team_id: '15', oponent_name:'New Zealand', opponent_result:'32', opponent_id: '13')
Result.create(round:'6', score: '19', team_name: 'Argentina', team_id: '16', oponent_name:'Australia', opponent_result:'25', opponent_id: '14')

